apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sno01030
  namespace: sno01030
spec:
  clusterName: sno01030
  clusterNamespace: sno01030
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect

  observability:
    enabled: false

  iamPolicyController:
    enabled: false

  policyController:
    enabled: false

  searchCollector:
    enabled: false

  workManager:
    enabled: true

  certPolicyController:
    enabled: false

  applicationManager:
    enabled: false
